### ISSUE TITLE
editing pads & calcs through share links not possible anymore.

### ISSUE THREAD

**Issue by quenenni** [otetard/ownpad#92] opened 2019-10-31 15:13 UTC
Someone reported to me that sharing a pad or calc file (public link) with the "Allow modification" setting on won't open the pad or calc anymore.

Nextcloud just offers now to download the file (not usefull as desktops don't recognise these files)

I updated all our Nc instances to last version of Nc 15 last month and that coincide with that someone's timing.
He was on 15.0.4 before, and now on 15.0.12.

I tested all the options I could, but only had the download button.

Is that a feature that was removed (couldn't info on that) or is it not working as intended?

**Comment by otetard** [comment] 2019-10-31 21:02
AFAIK, public sharing never worked. This is a duplicate of #30. I don't have enough free time to work on such feature these days.

**Closed by otetard** 2019-10-31 21:02 UTC
