### ISSUE TITLE
inputline for ext. pad missing

### ISSUE THREAD

**Issue by Manuelibt** [otetard/ownpad#17] opened 2017-02-16 17:13 UTC
Hi, 

i'm trying to set up the ownpad on my nextcloud installation. The inputline for the link is not showing after enabling Etherpad (admin -> Collaborative documents). Is this a common issue? Do i have to change the settings in my etherpad?

**Comment by Manuelibt** [comment] 2017-03-08 10:53
Am I the only one with this problem?

**Comment by otetard** [comment] 2017-03-08 14:40
Hi,

I don’t have this issue on my installations. 

What version of Nextcloud/ownCloud are you using? What happen if you enable Etherpad support and then refresh the settings page?

Olivier;

**Comment by Manuelibt** [comment] 2017-03-09 10:26
Hi, 

i'm using the 11.0.2. nextcloud version. When i'm enable the support and refreshing the page it is disabled again.. And there is no error regarding this issue in the logs.

**Comment by Manuelibt** [comment] 2017-03-29 15:05
No News with this issue?

**Comment by otetard** [comment] 2017-05-22 13:47
Sorry, I’m not able to reproduce that issue (and IFAIK, you are the only one that encounter that issue).

Could you tell me more about your environment (OS, browser, etc.)?

Olivier;

**Comment by Manuelibt** [comment] 2017-09-26 10:16
sorry for not answering for so long.. 
I am using different kind browsers and the problem appears everywhere...
The server is a webserver instance of all-ink. Don't know what kind of OS they are using..

**Comment by otetard** [comment] 2018-01-31 13:15
@Manuelibt Are you still facing this issue with the latest version (0.6.4)?

Olivier;

**Comment by Manuelibt** [comment] 2018-02-04 16:45
Hi Olivier, 

the problem is still there.. I attached a screenshot.

![ownpad](https://user-images.githubusercontent.com/20125642/35779793-275894fc-09d3-11e8-96e8-022d4cd109e5.png)

**Comment by otetard** [comment] 2018-02-12 15:34
Hi @Manuelibt,

I didn’t manage to reproduce your issue unfortunately (using Nextcloud 13 and Ownpad 0.6.5).

Let’s try to find the root of this issue. Could you answer to all of this questions please?

1. Are you able to change other settings on this page? When you update your settings, a password could be asked. If you enter a wrong one, modifications aren’t saved. 
2. If you enable Etherpad support in Ownpad’s configuration page, is the “Etherpad Host” input displayed? It should be displayed immediately (using jQuery/JavaScript).
3. What versions of Nextcloud and Ownpad are you using?
4. Is your Nextcloud installation fully working?
5. What is your browser?

Thanks!
Olivier;

**Comment by Manuelibt** [comment] 2018-02-12 22:43
Hi, 
will answer them with pleasure ;). 

1. Yes, I'm able to change different settings. Question for my password is just appearing from time to time. Not during the last 3 changes. 
2. No there is nothing displayed. 
3. 12.0.5 (I have to wait for a backup, for the next update..) and ownpad 0.6.5.
4. no other issues except  
5. firefox and chromium

Tell me if i can help somehow..

Manuel

**Comment by otetard** [comment] 2023-08-08 13:25
I’m closing this issue since this is a very old one. Please open a new issue if you still encounter this issue with the latest version of Ownpad!

**Closed by otetard** 2023-08-08 13:25 UTC
Labels: bug
